Traceback (most recent call last):
  File "/home/mikkel/discbot/IntFar/src/discord_bot.py", line 212, in poll_for_game_end
    await self.declare_intfar()
  File "/home/mikkel/discbot/IntFar/src/discord_bot.py", line 776, in declare_intfar
    self.active_game, filtered_stats, self.users_in_game)
  File "/home/mikkel/discbot/IntFar/src/database.py", line 221, in record_stats
    max_kda_id, stats = game_stats.get_outlier(data, "kda", asc=False)
  File "/home/mikkel/discbot/IntFar/src/game_stats.py", line 35, in get_outlier
    sorted_data = sorted(data, key=lambda entry: entry[1][key], reverse=not asc)
  File "/home/mikkel/discbot/IntFar/src/game_stats.py", line 35, in <lambda>
    sorted_data = sorted(data, key=lambda entry: entry[1][key], reverse=not asc)
KeyError: 'kda'
Traceback (most recent call last):
  File "/home/mikkel/discbot/IntFar/src/discord_bot.py", line 215, in poll_for_game_end
    await self.declare_intfar()
  File "/home/mikkel/discbot/IntFar/src/discord_bot.py", line 749, in declare_intfar
    for (count, (reason_index, stat_value)) in enumerate(intfar_data[final_intfar]):
KeyError: 255425791276482572
Traceback (most recent call last):
  File "/home/mikkel/discbot/IntFar/src/discord_bot.py", line 221, in poll_for_game_end
    await self.declare_intfar()
  File "/home/mikkel/discbot/IntFar/src/discord_bot.py", line 846, in declare_intfar
    self.database.record_stats(final_intfar, reasons_str, doinks,
UnboundLocalError: local variable 'final_intfar' referenced before assignment
Traceback (most recent call last):
  File "/home/mikkel/discbot/IntFar/src/discord_bot.py", line 221, in poll_for_game_end
    await self.declare_intfar()
  File "/home/mikkel/discbot/IntFar/src/discord_bot.py", line 774, in declare_intfar
    if not self.riot_api.is_summoners_rift(game_info["mapId"]):
TypeError: 'NoneType' object is not subscriptable
